version: "3"
services:
  postgres:
    image: postgres:16.3-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    ports:
      - "${POSTGRES_PORT-5432}:${POSTGRES_PORT-5432}"
